// src/components/ui/parallax-scrolling.tsx
'use client';

import { useEffect, useRef } from 'react';
import gsap from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';

import { acquireSmoothScroll } from '@/lib/smooth-scroll';

// The four layers are generated by `scripts/gen_parallax_layers.py` into
// public/parallax/. Drop a real screenshot at public/parallax/custom-layer-2.png
// and it replaces the mid layer with no code change -- the <img> falls back
// to the generated SVG if that file is not there.
const LAYER_1 = 'parallax/layer-1.svg';
const LAYER_2 = 'parallax/layer-2.svg';
const LAYER_2_CUSTOM = 'parallax/custom-layer-2.png';
const LAYER_3 = 'parallax/layer-3.svg';
const LAYER_4 = 'parallax/layer-4.svg';

export interface ParallaxComponentProps {
  title?: string;
  caption?: string;
}

export function ParallaxComponent({
  title = 'Assay',
  caption = 'Every deduction, recomputed from your contract.',
}: ParallaxComponentProps) {
  const parallaxRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    gsap.registerPlugin(ScrollTrigger);

    const triggerElement = parallaxRef.current?.querySelector('[data-parallax-layers]');

    if (triggerElement) {
      const tl = gsap.timeline({
        scrollTrigger: {
          trigger: triggerElement,
          start: "0% 0%",
          end: "100% 0%",
          scrub: 0
        }
      });

      const layers = [
        { layer: "1", yPercent: 70 },
        { layer: "2", yPercent: 55 },
        { layer: "3", yPercent: 40 },
        { layer: "4", yPercent: 10 }
      ];

      layers.forEach((layerObj, idx) => {
        tl.to(
          triggerElement.querySelectorAll(`[data-parallax-layer="${layerObj.layer}"]`),
          {
            yPercent: layerObj.yPercent,
            ease: "none"
          },
          idx === 0 ? undefined : "<"
        );
      });
    }

    const releaseSmoothScroll = acquireSmoothScroll();

    return () => {
      // Only this component's triggers, not every trigger on the page --
      // the original `ScrollTrigger.getAll().forEach(kill)` also killed the
      // hero's and the line story's.
      ScrollTrigger.getAll()
        .filter((st) => parallaxRef.current?.contains(st.trigger as Node))
        .forEach((st) => st.kill());
      if (triggerElement) gsap.killTweensOf(triggerElement);
      releaseSmoothScroll();
    };
  }, []);

  return (
    <div className="parallax" ref={parallaxRef}>
      <section className="parallax__header">
        <div className="parallax__visuals">
          <div className="parallax__black-line-overflow"></div>
          <div data-parallax-layers className="parallax__layers">
            <img src={LAYER_1} loading="eager" width="1600" data-parallax-layer="1" alt="" className="parallax__layer-img" />
            <img
              src={LAYER_2_CUSTOM}
              loading="eager"
              width="1600"
              data-parallax-layer="2"
              alt=""
              className="parallax__layer-img"
              onError={(e) => {
                // No custom screenshot dropped in -- use the generated layer.
                const img = e.currentTarget;
                if (!img.src.endsWith(LAYER_2)) img.src = LAYER_2;
              }}
            />
            <img src={LAYER_3} loading="eager" width="1600" data-parallax-layer="2" alt="" className="parallax__layer-img parallax__layer-img--strip" />
            <div data-parallax-layer="3" className="parallax__layer-title">
              <h2 className="parallax__title">{title}</h2>
              <p className="parallax__caption">{caption}</p>
            </div>
            <img src={LAYER_4} loading="eager" width="1600" data-parallax-layer="4" alt="" className="parallax__layer-img" />
          </div>
          <div className="parallax__fade"></div>
        </div>
      </section>
    </div>
  );
}

export default ParallaxComponent;
