/* The document `recursive-erosion.tsx` renders inside its sandboxed iframe.
 *
 * This file was NOT part of the pasted component -- the component imports it
 * and it did not exist -- so it is authored here to the contract the wrapper
 * expects: a complete HTML document exposing `#stage` as the element that
 * gets promoted to the fixed background, plus `#badge` and `.sr` for the
 * wrapper to hide.
 *
 * Deliberately dependency-free 2D canvas, not three.js from a CDN. The
 * iframe is `sandbox="allow-scripts"` with no `allow-same-origin`, so it has
 * an opaque origin; pulling a script over the network from inside it is both
 * a privacy leak and a blank-background-if-offline risk. A few thousand
 * points on a 2D context costs less than the WebGL context would anyway,
 * which matters when this thing sits behind an entire scrolling page.
 *
 * Palette is the reviewer's: near-black ground, cool greys, and gold used on
 * a small minority of points -- the same "gold means unreconciled" grammar
 * the rest of the site uses.
 */

export const recursiveErosionSource = [
  "<!doctype html>",
  '<html lang="en">',
  "<head>",
  '<meta charset="utf-8">',
  '<meta name="viewport" content="width=device-width, initial-scale=1">',
  "<title>Recursive Erosion</title>",
  "<style>",
  "  html,body{margin:0;height:100%;background:#08090b;overflow:hidden;}",
  "  #stage{position:fixed;inset:0;width:100%;height:100%;}",
  "  canvas{display:block;width:100%;height:100%;}",
  "  #badge,.sr{position:absolute;left:-9999px;}",
  "</style>",
  "</head>",
  "<body>",
  '<div id="stage"><canvas id="c"></canvas></div>',
  '<div id="badge">recursive erosion</div>',
  '<p class="sr">Ambient particle sphere background.</p>',
  "<script>",
  "(function(){",
  "  var canvas = document.getElementById('c');",
  "  var ctx = canvas.getContext('2d', { alpha: false });",
  "  var reduce = window.matchMedia && window.matchMedia('(prefers-reduced-motion: reduce)').matches;",
  "  var dpr = Math.min(window.devicePixelRatio || 1, 1.5);",
  "  var w = 0, h = 0;",
  "",
  "  function resize(){",
  "    w = window.innerWidth; h = window.innerHeight;",
  "    canvas.width = Math.floor(w * dpr); canvas.height = Math.floor(h * dpr);",
  "    ctx.setTransform(dpr, 0, 0, dpr, 0, 0);",
  "  }",
  "  resize();",
  "  window.addEventListener('resize', resize);",
  "",
  "  /* Seeded, so the field is identical on every load. */",
  "  var seed = 42;",
  "  function rnd(){",
  "    seed = (seed + 0x6D2B79F5) | 0;",
  "    var t = Math.imul(seed ^ (seed >>> 15), 1 | seed);",
  "    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;",
  "    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;",
  "  }",
  "",
  "  var COUNT = w < 720 ? 2000 : 4600;",
  "  var pts = [];",
  "  for (var i = 0; i < COUNT; i++){",
  "    /* Fibonacci sphere: even coverage without clumping at the poles. */",
  "    var k = i + 0.5;",
  "    var phi = Math.acos(1 - 2 * k / COUNT);",
  "    var theta = Math.PI * (1 + Math.sqrt(5)) * k;",
  "    /* Erosion: each point keeps a decay phase, so the shell thins and",
  "       refills in slow recursive waves rather than pulsing as one body. */",
  "    pts.push({",
  "      x: Math.sin(phi) * Math.cos(theta),",
  "      y: Math.sin(phi) * Math.sin(theta),",
  "      z: Math.cos(phi),",
  "      erode: rnd(),",
  "      rate: 0.04 + rnd() * 0.16,",
  "      gold: rnd() < 0.045",
  "    });",
  "  }",
  "",
  "  var t0 = 0;",
  "  function draw(now){",
  "    var time = now * 0.00006;",
  "    ctx.fillStyle = '#08090b';",
  "    ctx.fillRect(0, 0, w, h);",
  "",
  "    var cx = w * 0.5, cy = h * 0.5;",
  "    var radius = Math.min(w, h) * 0.58;",
  "    var ca = Math.cos(time), sa = Math.sin(time);",
  "    var cb = Math.cos(time * 0.63), sb = Math.sin(time * 0.63);",
  "",
  "    for (var i = 0; i < pts.length; i++){",
  "      var p = pts[i];",
  "      /* Rotate Y then X. */",
  "      var x1 = p.x * ca - p.z * sa;",
  "      var z1 = p.x * sa + p.z * ca;",
  "      var y1 = p.y * cb - z1 * sb;",
  "      var z2 = p.y * sb + z1 * cb;",
  "",
  "      var wave = 0.5 + 0.5 * Math.sin(time * 6.0 + p.erode * 6.283 + z2 * 2.2);",
  "      var alive = 0.28 + 0.72 * wave * wave;",
  "      if (alive < 0.06) continue;",
  "",
  "      var depth = (z2 + 1) * 0.5;",
  "      var scale = 0.55 + depth * 0.45;",
  "      var sx = cx + x1 * radius * scale;",
  "      var sy = cy + y1 * radius * scale;",
  "      var size = (p.gold ? 2.6 : 1.75) * scale;",
  "      var alpha = alive * (0.52 + depth * 0.48);",
  "",
  "      ctx.globalAlpha = p.gold ? Math.min(1, alpha * 1.7) : alpha;",
  "      ctx.fillStyle = p.gold ? '#e8b44a' : '#c3ccd8';",
  "      ctx.beginPath();",
  "      ctx.arc(sx, sy, size, 0, 6.283185);",
  "      ctx.fill();",
  "    }",
  "    ctx.globalAlpha = 1;",
  "    if (!reduce) t0 = requestAnimationFrame(draw);",
  "  }",
  "",
  "  if (reduce) { draw(12000); } else { t0 = requestAnimationFrame(draw); }",
  "",
  "  /* A background must never keep a hidden tab busy. */",
  "  document.addEventListener('visibilitychange', function(){",
  "    if (document.hidden) { cancelAnimationFrame(t0); }",
  "    else if (!reduce) { t0 = requestAnimationFrame(draw); }",
  "  });",
  "})();",
  "</script>",
  "</body>",
  "</html>",
].join("\n");

export default recursiveErosionSource;
